### ISSUE TITLE
Voonder Veapons Road Map to Release 1.0.0

### ISSUE THREAD

**Issue by CodeOvrLd** [CodeOvrLd/VoonderVeapons#7]
## Pre-Release

Going to get the pre-release out tonight. 

## Versions 0.x.0

Will Contain the next Tier of Guns 

## Version 1.0.0 

Will contain the complete set of Ammo/Weapons that will be offered. Still deciding if the modifications will be VonderVeapons modifications or if I will create a new mod. (Probably a new Mod)

**Comment by CodeOvrLd** [comment]
- [ ] Refactor code
- [ ] Double Check Spelling 
- [ ] Provide Translation Localization for foreign languages
- [ ] Tutorial Video 
- [ ] Proffer Video
- Mode Advertising materials
    - [ ] Picture showing all Punch Pack'd Guns
    - [ ] Picture showing all Vounderful Veapons
    - [ ] Title Screen for 1.0
    - Description
      - [ ] Introduction: 
      - [ ] body: 
      - [ ] Installation:
      - [ ] Support: 
      - [ ] GitHub, Github Project Board, GitHub Issue's link

**Comment by CodeOvrLd** [comment]
It is mature enough that we are not going to offer proffer materials. No video tutorials explaining how things are done. It will be obvious. 

### NEED AN ANSWER 
do we just expand teh Pre-Release bundles to include all offerings of weapons and just say that people only get 1 chance at spawn to get one of these great weapons and thats it? Do we allow crafting of them and then revamp for 2.0? I am curious how it will be recieved if you cant craft the weapons. 


### Answer 
Dont worry, be happy. Lets just drop it like its hot, but still expand on the bundle idea, do what we are doing 1  T0 (actually highest tier) and 1 random other gun. Need more boxes and localizations for them

**Comment by CodeOvrLd** [comment]
# Introduction
VoonderVeapons is a take on Call of Duty's Nazi Zombies. The goal of the mod is to add in the WonderWaffe DG-2 into the world of 7 days to die. There is nothing like shocking a group of enemies in place while you run away to safety. The initial offering of the mod came with the DeeGee:EyeVee a modified Pipe Pistol that shoots Ricochet Ammo. When the ammo impacts the output is discharged to all other zombies around it. If its wind, everyone gets blown away, fire ignites, ice slows down, and lighting shocks.  This mod is fun based, let's get some.

**Comment by CodeOvrLd** [comment]
# Body
VoonderVeapons 1.0: The Upgraded Guns/ServerSide/International Update
We have strived to bring more elements of CoD Nazi Zombies into 7 days to die. This update is adding in a Tiered system of Weapons that are an upgraded version of the vanilla guns. Not all guns have been upgraded but the ones that have are colored differently where possible. The guns are crafted using the standard game perks and recipes in the Workbench. There is no barrier besides the work bench to upgrade weapons as long as you have the dukes for it. 

Removed: Clientside necessary files. We are no longer using custom images and icons. We will use the game assets from this point forward as to keep it as a server side mod.

Added: Complete Translation of the all game assets. Users in 12 languages can enjoy VoonderVeapons in their own language. 

Added: VoonderVeapon Ammo Cartridge(9mm), and Rounds(7.62mm) status effect ammo. 

Added: VoonderVeapon's Fall's Squeal and The Exploder, a handgun and rifle variant of the DeeGee:EyeVee without the Ricochett aspect. 

Added: Moose Tangano Sally, E-Nuf Shot, HarmMaGiddeon, Viper, V-Ray Gun, E-Nuf Shot Mk II, 1K Kamikaze, Ztaps-744, 210 Piercer, The Beforburner, G0500, Sphyraena 11A-UF, The Stranger Danger, and the Infiltrator. Each of these weapons uses the standard vanilla ammo types, they are the upgraded versions of the original guns. 

Early Adopters will receive a free gift on fresh spawn in the world. Enjoy the gift and look out for the next update.

**Comment by CodeOvrLd** [comment]
# Installation
1. Download the Zip
2. Extract the zip and place it in the 7 Days to Die Mods Folder
3. Enjoy

**Comment by CodeOvrLd** [comment]
#Support 
Discord Board: https://discord.gg/vvW586byeS

**Comment by CodeOvrLd** [comment]
# Holding Off 
Need to hold back to buff/debuff certian guns. Make a new issue and tackle that before it goes out.

**Comment by CodeOvrLd** [comment]
# Implemented 
- Weapons Balancing, Strategy for Tier Bonus Based upon Upgrade 
- Mister E Box Code

## Need to code the Mister E Box machine 
It should have 1 crafting slot, no fuel, and recipes, crafting recipe 
- Crafting Slot: I Want it to work like the real mystery box, user puts in the money and it takes time to spin the box: 30sec-45sec maybe
- No Fuel Window: It shouldn't use fuel it should use recipes
- Recipes: Only needs 1 Recipe, Mister  E Box = 9500 dukes (I might have 2 recipes, 1 for basic weapons when you are in the low tier and a second unlockable recipe that gives the guns I'm making. still deciding on this)
- Crafting Recipe: (Don't want to give this out too early cause you should have to get to mid game before you can queue up guns, i want to say Workbench and steel might be the safest bet)
    - Need to figure out Materials: 100 Steel, 10 handgun, 10 rifle, 10 shotgun. 10 machinegun parts (this makes it difficulty but not impossible) 
    - Workstation: Workbench
    - Game State: Mid Game, have to have the advanced engineering perk unlocked, or buy workbench/crucible/forge, or schematics for the items to craft. All these things scream mid game or really lucky early game. 

## Machine Mesh : cntMunitionsBoxGreen
- Going to use the munitions box as the Mister E Box. 
### Blockname: VoonderVeapons_MisterEBox
### BlockWindowName: workstation_VoonderVeapons_MisterEBox
### WindowItems: 
```
			<window name="windowCraftingList" />
			<window name="craftingInfoPanel" />
			<window name="windowCraftingQueue" />
			<window name="windowOutput" />
			<window name="windowNonPagingHeader" />```

**Comment by CodeOvrLd** [comment]
Clean up Comments and naming from the Above, Code is ripped from https://github.com/CodeOvrLd/xFiberCraft Loom

**Comment by CodeOvrLd** [comment]
# Moving the Goal Post 
1.0 Launch Will Include: 
- Base Guns for the future Upgrade Machines
- Mister E Box to allow Users to gain the guns instead of crafting with money 
- Remove: Recipes to craft VoonderVeapons. For this first release you get a gun on spawn but then have to wait until you can create a Mister E Box before you gain access to all of the guns

2.0 Looking Forward
- Add: Pack-A-Punch machine which will take the current base weapons and give them the next level of upgrade, The Upgraded Tier Bonus for the first level of upgrade is: 
```
1st Pack a Punch Tier Bonus
T1: 26%
T2: 38%
T3: 46%
T4: 53%
T0: 60%
```
- Add: Gobble Gumball Machine that gives buff candies that accomplish and effect. 

3.0 Looking Forward
- Add: RePacked recipes so that the Pack-A-Punch can upgrade the current guns to the 2nd Pack a Punch
```
T1: 82%
T2: 86%
T3: 90%
T4: 94%
T5: 97%
T0: 100%
```

4.0 Looking Forward
- Add: Secondary Weapons, think Monkey Bombs, Russian Nesting Doll bombs, Gersch Devices, crossbow the detonation arrows. Hopefully by this point we know how to effectively use buffs and have a complete picture of gobble gums and upgraded weapons so we can add in the little stuff that makes it complete
- Add: The original Cola machines. These should be permanent buffs but we need to figure that out. I have seen topics in the community site about buffs that re-apply and never end. 
- Add: Gun Wall Buys, need to figure out the feasibility of this idea but we should have the ability to create gun wall buys that only sell a specific gun, unlock the Mister E Box that rolls a random gun. 
- Add: InstantKill, FireSale, Nuke, and Double Points. This might be hard but we need to do like the quest kind of thing and add in that you run to a marker, press "E" and a quest that has no objectives is completed and you are given a buff to do sutff. where the buff is AOE so all party memebers get the buff.

**Comment by CodeOvrLd** [comment]
#31
